default_config = {'root': {'font_size': 16, 'font_style': 'TkFixedFont', 'font_extra': 'bold'},
                  'config': {'button_width': 17, 'small_button_width': 7, 'button_height': 1, 'bg_color': '#1C1C1C'},
                  'main': {'width': 420, 'height': 690, 'relative_open_on_startup': True,
                           'fuel_open_on_startup': True},
                  'settings': {'width': 420, 'height': 950, 'block_width': 200, 'block_height': 100,
                               'checkbutton_width': 10},
                  'login': {'width': 420, 'height': 690, 'auto_login_activation': False},
                  'fuel': {'font_size': 16, 'text_padding': 5, 'offset_right': 5, 'offset_down': 5,
                           'fg_color_header': '#0061B7', 'fg_color_values': '#EAEAEA', 'fg_color_special': '#E12D5C',
                           'fuel_activated': True, 'last_activated': True, 'avg_activated': True,
                           'target_activated': True, 'range_activated': True, 'refuel_activated': True,
                           'finish_activated': True, 'remaining_activated': True, 'safety_margin': 5},
                  'relative': {'font_size': 12, 'text_padding_x': 3, 'text_padding_y': 2, 'offset_right': 1350,
                               'offset_down': 850, 'hide_pits': False, 'license_activated': True,
                               'irating_activated': True}}
