name: Executable Build - Nuitka

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

env:
  APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
  REGION: ${{ secrets.REGION }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Check-out repository
    - name: Check-out the repository
      uses: actions/checkout@v3

    # Setup Python
    - name: Setup the python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        cache: 'pip'
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build python script into a stand-alone exe
    - name: Build the executable using Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
        script-name: RacingInsightsApp.py
        module: false
        standalone: true
        onefile: true
        assume-yes-for-downloads: true
        enable-plugins: tk-inter

#        include-package: src
#        include-package-data:
#        include-module:
#        include-plugin-directory:
#        include-plugin-files:
#        prefer-source-code:

        # if onefile true:
        output-dir: .
        # elif onefile false, use the following
#        output-dir: build/

#        output-file: # Cannot be changed in standalone mode
#        access-token:
        enable-console: false
        disable-console: true
        windows-icon-from-ico: images/RacingInsights_logo.ico
#        windows-uac-admin: false
#        windows-uac-uiaccess: false
        windows-company-name: Qnooperd
        windows-product-name: RacingInsights
        windows-file-version: 0.0.2.0
        windows-product-version: 0.0.2.0
#        windows-file-description:
#        windows-onefile-tempdir-spec:
#        macos-create-app-bundle:

    # if onefile false, use the following
#    - name: Arrange the files
#      run: |
#        copy "./images/" "/build/images/"

    # Uploads artifact
    - name: Upload the build output as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: RacingInsights-App
#        path: |
#          ./build/
        path: |
          RacingInsightsApp.exe
          ./images/

        if-no-files-found: error
